name: CI

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: install
        run: npm install

      - name: typecheck
        run: npm run typecheck

      - name: lint
        run: npm run lint

      - name: test
        run: npm run test

      - name: build
        run: npm run build
